[tools]
"aqua:goreleaser/goreleaser" = "2.12.5"
"aqua:suzuki-shunsuke/pinact" = "3.4.2"
"npm:@ast-grep/cli" = "0.39.6"
"npm:@augmentcode/auggie" = "0.5.8"
"npm:@charmland/crush" = "0.10.4"
"npm:@github/copilot" = "0.0.339"
"npm:@openai/codex" = "0.46.0"
1password-cli = "2.32.0"
bun = "1.3.0"
gh = "2.81.0"
ghq = "1.8.0"
jq = "1.8.1"
lazydocker = "0.24.1"
node = "24.9.0"
rust = "1.90.0"
uv = "0.9.2"

[settings]
experimental = true
lockfile = true
idiomatic_version_file_enable_tools = []

