[tools]
"aqua:goreleaser/goreleaser" = "2.12.7"
"aqua:suzuki-shunsuke/pinact" = "3.4.4"
"npm:@ast-grep/cli" = "0.40.0"
"npm:@augmentcode/auggie" = "0.9.1"
"npm:@charmland/crush" = "0.18.5"
"npm:@github/copilot" = "0.0.362"
"npm:@openai/codex" = "0.63.0"
"npm:@anthropic-ai/claude-code" = "latest"
1password-cli = "2.32.0"
bun = "1.3.3"
gh = "2.83.1"
ghq = "1.8.0"
jq = "1.8.1"
lazydocker = "0.24.2"
node = "latest"
rust = "1.91.1"
uv = "0.9.11"

[settings]
experimental = true
lockfile = true
idiomatic_version_file_enable_tools = []

